image: robert96/tox

stages:
  - test
  - deploy

test:py36:
  stage: test
  script:
    - tox -e py36

test:py37:
  stage: test
  script:
    - tox -e py37

test:py38:
  stage: test
  script:
    - tox -e py38

test:py39:
  stage: test
  script:
    - tox -e py39

test:pypy36:
  script:
    - tox -e pypy36

lint:
  stage: test
  script:
    - tox -e flake8

pypi:
  stage: deploy
  script:
    - python3.6 -m pip install twine wheel
    - python3.6 setup.py sdist bdist_wheel
    - python3.6 -m twine upload dist/*
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant
