stages:
  - test
  - deploy

pytest:
  image: docker.io/fpob/poetry:$TAG
  stage: test
  script:
    - apt update && apt install -y librhash0
    - poetry install
    - poetry run poe pytest
  parallel:
    matrix:
      - TAG:
          - py39
          - py310
          - py311
          - pypy39

mypy:
  image: docker.io/fpob/poetry:latest
  stage: test
  script:
    - poetry install
    - poetry run poe mypy

flake8:
  image: docker.io/fpob/poetry:latest
  stage: test
  script:
    - poetry install
    - poetry run poe flake8

pages:
  image: docker.io/fpob/poetry:latest
  stage: deploy
  script:
    - poetry install
    - poetry run poe docs
    - mv build/docs public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

package:
  image: docker.io/fpob/poetry:latest
  stage: deploy
  script:
    - poetry publish --build --repository
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
