version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  apt_packages:
    - librhash0
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install

sphinx:
  configuration: docs/conf.py
