[project]
name = "yumemi"
version = "2.1.0"
description = "AniDB API library for Python and simple CLI client"
readme = "README.rst"
authors = [{name = "Filip Pobořil", email = "dev@fpob.cz"}]
license = "MIT"
keywords = ["AniDB"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: End Users/Desktop",
  "Topic :: Utilities",
]
requires-python = ">=3.9"
dependencies = [
  "click",
  "attrs",
  "cryptography"
]

[project.urls]
Repository = "https://github.com/fpob/yumemi"
Documentation = "https://yumemi.readthedocs.io/"

[project.scripts]
yumemi = "yumemi.cli:main"


[dependency-groups]
dev = [
  "pytest",
  "pytest-mock",
  "mypy",
  "pyproject-flake8",
  "flake8-bugbear",
  "flake8-isort",
  "isort",
  "furo",
  "sphinx",
  "sphinx-click",
  "poethepoet",
]


[tool.poe.tasks]
pytest = "pytest"
mypy = "mypy src"
flake8 = "pflake8 src tests"
isort = "isort src tests"
docs = "sphinx-build -a docs build/docs"


[tool.pytest.ini_options]
addopts = "-ra -v"
pythonpath = ["src"]


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
namespace_packages = true
install_types = true
non_interactive = true

[[tool.mypy.overrides]]
module = "yumemi._rhash.*"
ignore_errors = true


[tool.flake8]
max-line-length = 80
select = "C,E,F,W,B,B950,I"
ignore = "W503,E501"
exclude = "src/yumemi/_rhash"


[tool.isort]
lines_after_imports = 2
line_length = 88
extend_skip = ["src/yumemi/_rhash"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
