name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build package
        run: hatch build

      - name: Create GitHub release
        run: gh release create --repo ${{ github.repository }} ${{ github.ref_name }} dist/*
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish to PyPI
        run: hatch publish
        env:
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}

      - name: Update tag "stable"
        uses: rickstaa/action-create-tag@v1
        with:
          tag: stable
          force_push_tag: true
