name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - 'pypy3.9'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instal RHash
        run: |
          sudo apt-get update
          sudo apt-get install librhash0

      - name: Run poetry install
        run: poetry install

      - name: Run poe pytest
        run: poetry run poe pytest

  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - mypy
          - flake8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run poetry install
        run: poetry install

      - name: Run poe ${{ matrix.task }}
        run: poetry run poe ${{ matrix.task }}
